# Generic Dockerfile template for all tools that need to be built.
#
# Our Codebuild setup assumes each image has its own Dockerfile. It
# names the resulting image based on the name of the directory in which it
# finds the Dockerfile. It does not allow passing arbitrary build arguments.
# It runs "make all" before looking up up the Dockerfiles.
#
# This file is meant to be used by Make to generate the actual Dockerfile
# for each Go package that is meant to be turned into a Docker image. This is
# done by substituting the BGDI_GO_PACKAGE string with the name of the
# directory/package into which the Dockerfile is generated.

ARG BASE_IMAGE_VERSION=YOU_FORGOT_TO_SET_A_VERSION
# Use an official Golang image as the base
FROM golang:${BASE_IMAGE_VERSION} AS builder

WORKDIR /tool

# Copy go.mod and go.sum first to leverage caching
COPY go.mod go.sum ./
RUN go mod tidy

# Copy the entire project (including shared libraries)
COPY . .

# Build only the specific tool
RUN CGO_ENABLED=0 go build -o BGDI_GO_PACKAGE.bin ./BGDI_GO_PACKAGE

# Create a minimal runtime image
FROM alpine:latest

ARG GIT_HASH=unknown
ARG GIT_BRANCH=unknown
ARG GIT_DIRTY=""
ARG VERSION=unknown
ARG AUTHOR=unknown
LABEL git.hash=$GIT_HASH
LABEL git.branch=$GIT_BRANCH
LABEL git.dirty="$GIT_DIRTY"
LABEL version=$VERSION
LABEL author=$AUTHOR

# Create a user and group (non-root)
RUN addgroup -S geoadmin && adduser -S geoadmin -G geoadmin

# Install certificates (needed for HTTPS requests)
# RUN apk --no-cache add ca-certificates

# Set the working directory
WORKDIR /root/

# Copy the built binary from the builder stage
COPY --from=builder /tool/BGDI_GO_PACKAGE.bin BGDI_GO_PACKAGE

# # Set execution permissions
RUN chmod +x BGDI_GO_PACKAGE

USER geoadmin

# Default command when running the container
ENTRYPOINT ["./BGDI_GO_PACKAGE"]
CMD []
